/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDatasource,
  CreateDocument,
  Datasource,
  Document,
} from '../models/index';
import {
    CreateDatasourceFromJSON,
    CreateDatasourceToJSON,
    CreateDocumentFromJSON,
    CreateDocumentToJSON,
    DatasourceFromJSON,
    DatasourceToJSON,
    DocumentFromJSON,
    DocumentToJSON,
} from '../models/index';

export interface DatasourcesControllerCreateDatasourceRequest {
    createDatasource: CreateDatasource;
}

export interface DatasourcesControllerCreateDocumentRequest {
    createDocument: CreateDocument;
}

export interface DatasourcesControllerGetDatasourceByIdRequest {
    datasourceId: number;
}

export interface DatasourcesControllerGetDatasourcesForConversationRequest {
    conversationId: string;
}

export interface DatasourcesControllerGetDocumentByIdRequest {
    documentId: number;
}

export interface DatasourcesControllerGetDocumentsForConversationRequest {
    conversationId: string;
}

export interface DatasourcesControllerGetDocumentsForDatasourceRequest {
    datasourceId: number;
}

/**
 * 
 */
export class DatasourcesApi extends runtime.BaseAPI {

    /**
     * Create a new datasource
     */
    async datasourcesControllerCreateDatasourceRaw(requestParameters: DatasourcesControllerCreateDatasourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Datasource>> {
        if (requestParameters['createDatasource'] == null) {
            throw new runtime.RequiredError(
                'createDatasource',
                'Required parameter "createDatasource" was null or undefined when calling datasourcesControllerCreateDatasource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/datasources`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDatasourceToJSON(requestParameters['createDatasource']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatasourceFromJSON(jsonValue));
    }

    /**
     * Create a new datasource
     */
    async datasourcesControllerCreateDatasource(requestParameters: DatasourcesControllerCreateDatasourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Datasource> {
        const response = await this.datasourcesControllerCreateDatasourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new document
     */
    async datasourcesControllerCreateDocumentRaw(requestParameters: DatasourcesControllerCreateDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Document>> {
        if (requestParameters['createDocument'] == null) {
            throw new runtime.RequiredError(
                'createDocument',
                'Required parameter "createDocument" was null or undefined when calling datasourcesControllerCreateDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/datasources/documents`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDocumentToJSON(requestParameters['createDocument']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentFromJSON(jsonValue));
    }

    /**
     * Create a new document
     */
    async datasourcesControllerCreateDocument(requestParameters: DatasourcesControllerCreateDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Document> {
        const response = await this.datasourcesControllerCreateDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get datasource by ID
     */
    async datasourcesControllerGetDatasourceByIdRaw(requestParameters: DatasourcesControllerGetDatasourceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Datasource>> {
        if (requestParameters['datasourceId'] == null) {
            throw new runtime.RequiredError(
                'datasourceId',
                'Required parameter "datasourceId" was null or undefined when calling datasourcesControllerGetDatasourceById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/datasources/{datasourceId}`.replace(`{${"datasourceId"}}`, encodeURIComponent(String(requestParameters['datasourceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatasourceFromJSON(jsonValue));
    }

    /**
     * Get datasource by ID
     */
    async datasourcesControllerGetDatasourceById(requestParameters: DatasourcesControllerGetDatasourceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Datasource> {
        const response = await this.datasourcesControllerGetDatasourceByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all datasources for a conversation
     */
    async datasourcesControllerGetDatasourcesForConversationRaw(requestParameters: DatasourcesControllerGetDatasourcesForConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Datasource>>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling datasourcesControllerGetDatasourcesForConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/datasources/conversation/{conversationId}`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DatasourceFromJSON));
    }

    /**
     * Get all datasources for a conversation
     */
    async datasourcesControllerGetDatasourcesForConversation(requestParameters: DatasourcesControllerGetDatasourcesForConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Datasource>> {
        const response = await this.datasourcesControllerGetDatasourcesForConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get document by ID
     */
    async datasourcesControllerGetDocumentByIdRaw(requestParameters: DatasourcesControllerGetDocumentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Document>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling datasourcesControllerGetDocumentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/datasources/documents/{documentId}`.replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentFromJSON(jsonValue));
    }

    /**
     * Get document by ID
     */
    async datasourcesControllerGetDocumentById(requestParameters: DatasourcesControllerGetDocumentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Document> {
        const response = await this.datasourcesControllerGetDocumentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all documents for a conversation
     */
    async datasourcesControllerGetDocumentsForConversationRaw(requestParameters: DatasourcesControllerGetDocumentsForConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling datasourcesControllerGetDocumentsForConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/datasources/conversation/{conversationId}/documents`.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentFromJSON));
    }

    /**
     * Get all documents for a conversation
     */
    async datasourcesControllerGetDocumentsForConversation(requestParameters: DatasourcesControllerGetDocumentsForConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>> {
        const response = await this.datasourcesControllerGetDocumentsForConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all documents for a datasource
     */
    async datasourcesControllerGetDocumentsForDatasourceRaw(requestParameters: DatasourcesControllerGetDocumentsForDatasourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>> {
        if (requestParameters['datasourceId'] == null) {
            throw new runtime.RequiredError(
                'datasourceId',
                'Required parameter "datasourceId" was null or undefined when calling datasourcesControllerGetDocumentsForDatasource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/datasources/{datasourceId}/documents`.replace(`{${"datasourceId"}}`, encodeURIComponent(String(requestParameters['datasourceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentFromJSON));
    }

    /**
     * Get all documents for a datasource
     */
    async datasourcesControllerGetDocumentsForDatasource(requestParameters: DatasourcesControllerGetDocumentsForDatasourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>> {
        const response = await this.datasourcesControllerGetDocumentsForDatasourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
