/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateModel,
  Model,
  ModelType,
  UpdateModel,
} from '../models/index';
import {
    CreateModelFromJSON,
    CreateModelToJSON,
    ModelFromJSON,
    ModelToJSON,
    ModelTypeFromJSON,
    ModelTypeToJSON,
    UpdateModelFromJSON,
    UpdateModelToJSON,
} from '../models/index';

export interface CreateModelRequest {
    createModel: CreateModel;
}

export interface DeleteModelRequest {
    modelId: number;
}

export interface GetModelByIdRequest {
    modelId: number;
}

export interface UpdateModelRequest {
    modelId: number;
    updateModel: UpdateModel;
}

/**
 * 
 */
export class ModelsApi extends runtime.BaseAPI {

    /**
     * Create a new model
     */
    async createModelRaw(requestParameters: CreateModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model>> {
        if (requestParameters['createModel'] == null) {
            throw new runtime.RequiredError(
                'createModel',
                'Required parameter "createModel" was null or undefined when calling createModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/models`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateModelToJSON(requestParameters['createModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelFromJSON(jsonValue));
    }

    /**
     * Create a new model
     */
    async createModel(createModel: CreateModel, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model> {
        const response = await this.createModelRaw({ createModel: createModel }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a model
     */
    async deleteModelRaw(requestParameters: DeleteModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling deleteModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models/{modelId}`.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a model
     */
    async deleteModel(modelId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteModelRaw({ modelId: modelId }, initOverrides);
    }

    /**
     * Get all models for the authenticated member
     */
    async getAllModelsForMemberRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Model>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelFromJSON));
    }

    /**
     * Get all models for the authenticated member
     */
    async getAllModelsForMember(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Model>> {
        const response = await this.getAllModelsForMemberRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get model by ID
     */
    async getModelByIdRaw(requestParameters: GetModelByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model>> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getModelById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models/{modelId}`.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelFromJSON(jsonValue));
    }

    /**
     * Get model by ID
     */
    async getModelById(modelId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model> {
        const response = await this.getModelByIdRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Get all model types
     */
    async getModelTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models/model-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelTypeFromJSON));
    }

    /**
     * Get all model types
     */
    async getModelTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelType>> {
        const response = await this.getModelTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an existing model
     */
    async updateModelRaw(requestParameters: UpdateModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model>> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateModel().'
            );
        }

        if (requestParameters['updateModel'] == null) {
            throw new runtime.RequiredError(
                'updateModel',
                'Required parameter "updateModel" was null or undefined when calling updateModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/models/{modelId}`.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateModelToJSON(requestParameters['updateModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelFromJSON(jsonValue));
    }

    /**
     * Update an existing model
     */
    async updateModel(modelId: number, updateModel: UpdateModel, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model> {
        const response = await this.updateModelRaw({ modelId: modelId, updateModel: updateModel }, initOverrides);
        return await response.value();
    }

}
