/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiStatusUpdate
 */
export interface AiStatusUpdate {
    /**
     * 
     * @type {string}
     * @memberof AiStatusUpdate
     */
    topicId: string;
    /**
     * 
     * @type {string}
     * @memberof AiStatusUpdate
     */
    topic: string;
    /**
     * 
     * @type {object}
     * @memberof AiStatusUpdate
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof AiStatusUpdate
     */
    displayText: string;
    /**
     * 
     * @type {boolean}
     * @memberof AiStatusUpdate
     */
    isError: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AiStatusUpdate
     */
    topicCompleted: boolean;
    /**
     * 
     * @type {number}
     * @memberof AiStatusUpdate
     */
    date: number;
    /**
     * 
     * @type {number}
     * @memberof AiStatusUpdate
     */
    timeTakenInMs: number;
}

/**
 * Check if a given object implements the AiStatusUpdate interface.
 */
export function instanceOfAiStatusUpdate(value: object): value is AiStatusUpdate {
    if (!('topicId' in value) || value['topicId'] === undefined) return false;
    if (!('topic' in value) || value['topic'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('displayText' in value) || value['displayText'] === undefined) return false;
    if (!('isError' in value) || value['isError'] === undefined) return false;
    if (!('topicCompleted' in value) || value['topicCompleted'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('timeTakenInMs' in value) || value['timeTakenInMs'] === undefined) return false;
    return true;
}

export function AiStatusUpdateFromJSON(json: any): AiStatusUpdate {
    return AiStatusUpdateFromJSONTyped(json, false);
}

export function AiStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiStatusUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'topicId': json['topicId'],
        'topic': json['topic'],
        'data': json['data'],
        'displayText': json['displayText'],
        'isError': json['isError'],
        'topicCompleted': json['topicCompleted'],
        'date': json['date'],
        'timeTakenInMs': json['timeTakenInMs'],
    };
}

export function AiStatusUpdateToJSON(json: any): AiStatusUpdate {
    return AiStatusUpdateToJSONTyped(json, false);
}

export function AiStatusUpdateToJSONTyped(value?: AiStatusUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topicId': value['topicId'],
        'topic': value['topic'],
        'data': value['data'],
        'displayText': value['displayText'],
        'isError': value['isError'],
        'topicCompleted': value['topicCompleted'],
        'date': value['date'],
        'timeTakenInMs': value['timeTakenInMs'],
    };
}

