/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateUrl } from './CreateUrl';
import {
    CreateUrlFromJSON,
    CreateUrlFromJSONTyped,
    CreateUrlToJSON,
    CreateUrlToJSONTyped,
} from './CreateUrl';

/**
 * 
 * @export
 * @interface BatchCreateUrlRequest
 */
export interface BatchCreateUrlRequest {
    /**
     * Array of URLs to be shortened, each with an optional custom UUID
     * @type {Array<CreateUrl>}
     * @memberof BatchCreateUrlRequest
     */
    urls: Array<CreateUrl>;
}

/**
 * Check if a given object implements the BatchCreateUrlRequest interface.
 */
export function instanceOfBatchCreateUrlRequest(value: object): value is BatchCreateUrlRequest {
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function BatchCreateUrlRequestFromJSON(json: any): BatchCreateUrlRequest {
    return BatchCreateUrlRequestFromJSONTyped(json, false);
}

export function BatchCreateUrlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchCreateUrlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': ((json['urls'] as Array<any>).map(CreateUrlFromJSON)),
    };
}

export function BatchCreateUrlRequestToJSON(json: any): BatchCreateUrlRequest {
    return BatchCreateUrlRequestToJSONTyped(json, false);
}

export function BatchCreateUrlRequestToJSONTyped(value?: BatchCreateUrlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': ((value['urls'] as Array<any>).map(CreateUrlToJSON)),
    };
}

