/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatInference
 */
export interface ChatInference {
    /**
     * 
     * @type {string}
     * @memberof ChatInference
     */
    prompt: string;
}

/**
 * Check if a given object implements the ChatInference interface.
 */
export function instanceOfChatInference(value: object): value is ChatInference {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function ChatInferenceFromJSON(json: any): ChatInference {
    return ChatInferenceFromJSONTyped(json, false);
}

export function ChatInferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatInference {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
    };
}

export function ChatInferenceToJSON(json: any): ChatInference {
    return ChatInferenceToJSONTyped(json, false);
}

export function ChatInferenceToJSONTyped(value?: ChatInference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
    };
}

