/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessage
 */
export interface CreateMessage {
    /**
     * 
     * @type {string}
     * @memberof CreateMessage
     */
    messageText: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMessage
     */
    role: string;
}

/**
 * Check if a given object implements the CreateMessage interface.
 */
export function instanceOfCreateMessage(value: object): value is CreateMessage {
    if (!('messageText' in value) || value['messageText'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CreateMessageFromJSON(json: any): CreateMessage {
    return CreateMessageFromJSONTyped(json, false);
}

export function CreateMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'messageText': json['messageText'],
        'role': json['role'],
    };
}

export function CreateMessageToJSON(json: any): CreateMessage {
    return CreateMessageToJSONTyped(json, false);
}

export function CreateMessageToJSONTyped(value?: CreateMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageText': value['messageText'],
        'role': value['role'],
    };
}

