/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDocument
 */
export interface CreateDocument {
    /**
     * 
     * @type {string}
     * @memberof CreateDocument
     */
    text: string;
}

/**
 * Check if a given object implements the CreateDocument interface.
 */
export function instanceOfCreateDocument(value: object): value is CreateDocument {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreateDocumentFromJSON(json: any): CreateDocument {
    return CreateDocumentFromJSONTyped(json, false);
}

export function CreateDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function CreateDocumentToJSON(json: any): CreateDocument {
    return CreateDocumentToJSONTyped(json, false);
}

export function CreateDocumentToJSONTyped(value?: CreateDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

