/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDatasource
 */
export interface CreateDatasource {
    /**
     * 
     * @type {number}
     * @memberof CreateDatasource
     */
    datasourceTypeId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDatasource
     */
    name: string;
}

/**
 * Check if a given object implements the CreateDatasource interface.
 */
export function instanceOfCreateDatasource(value: object): value is CreateDatasource {
    if (!('datasourceTypeId' in value) || value['datasourceTypeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateDatasourceFromJSON(json: any): CreateDatasource {
    return CreateDatasourceFromJSONTyped(json, false);
}

export function CreateDatasourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatasource {
    if (json == null) {
        return json;
    }
    return {
        
        'datasourceTypeId': json['datasourceTypeId'],
        'name': json['name'],
    };
}

export function CreateDatasourceToJSON(json: any): CreateDatasource {
    return CreateDatasourceToJSONTyped(json, false);
}

export function CreateDatasourceToJSONTyped(value?: CreateDatasource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datasourceTypeId': value['datasourceTypeId'],
        'name': value['name'],
    };
}

