/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMemberPrompt
 */
export interface CreateMemberPrompt {
    /**
     * 
     * @type {string}
     * @memberof CreateMemberPrompt
     */
    promptName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberPrompt
     */
    promptText: string;
}

/**
 * Check if a given object implements the CreateMemberPrompt interface.
 */
export function instanceOfCreateMemberPrompt(value: object): value is CreateMemberPrompt {
    if (!('promptName' in value) || value['promptName'] === undefined) return false;
    if (!('promptText' in value) || value['promptText'] === undefined) return false;
    return true;
}

export function CreateMemberPromptFromJSON(json: any): CreateMemberPrompt {
    return CreateMemberPromptFromJSONTyped(json, false);
}

export function CreateMemberPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMemberPrompt {
    if (json == null) {
        return json;
    }
    return {
        
        'promptName': json['promptName'],
        'promptText': json['promptText'],
    };
}

export function CreateMemberPromptToJSON(json: any): CreateMemberPrompt {
    return CreateMemberPromptToJSONTyped(json, false);
}

export function CreateMemberPromptToJSONTyped(value?: CreateMemberPrompt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptName': value['promptName'],
        'promptText': value['promptText'],
    };
}

