/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConversation
 */
export interface CreateConversation {
    /**
     * 
     * @type {string}
     * @memberof CreateConversation
     */
    conversationName: string;
}

/**
 * Check if a given object implements the CreateConversation interface.
 */
export function instanceOfCreateConversation(value: object): value is CreateConversation {
    if (!('conversationName' in value) || value['conversationName'] === undefined) return false;
    return true;
}

export function CreateConversationFromJSON(json: any): CreateConversation {
    return CreateConversationFromJSONTyped(json, false);
}

export function CreateConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversation {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationName': json['conversationName'],
    };
}

export function CreateConversationToJSON(json: any): CreateConversation {
    return CreateConversationToJSONTyped(json, false);
}

export function CreateConversationToJSONTyped(value?: CreateConversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationName': value['conversationName'],
    };
}

