/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUrl
 */
export interface CreateUrl {
    /**
     * Optional custom UUID for the shortened URL. If not provided, a new UUID will be generated.
     * @type {string}
     * @memberof CreateUrl
     */
    id?: string;
    /**
     * The URL to be shortened
     * @type {string}
     * @memberof CreateUrl
     */
    originalUrl: string;
}

/**
 * Check if a given object implements the CreateUrl interface.
 */
export function instanceOfCreateUrl(value: object): value is CreateUrl {
    if (!('originalUrl' in value) || value['originalUrl'] === undefined) return false;
    return true;
}

export function CreateUrlFromJSON(json: any): CreateUrl {
    return CreateUrlFromJSONTyped(json, false);
}

export function CreateUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'originalUrl': json['originalUrl'],
    };
}

export function CreateUrlToJSON(json: any): CreateUrl {
    return CreateUrlToJSONTyped(json, false);
}

export function CreateUrlToJSONTyped(value?: CreateUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'originalUrl': value['originalUrl'],
    };
}

