/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateModel
 */
export interface CreateModel {
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    apiKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    modelName: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateModel
     */
    isDefault: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateModel
     */
    modelTypeId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    initialMessage: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    filePath: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateModel
     */
    contextSize: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateModel
     */
    additionalLlamacppServerParams: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateModel
     */
    prependNoThinkTagToBeginningOfEachMessage: boolean | null;
}

/**
 * Check if a given object implements the CreateModel interface.
 */
export function instanceOfCreateModel(value: object): value is CreateModel {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('modelTypeId' in value) || value['modelTypeId'] === undefined) return false;
    if (!('initialMessage' in value) || value['initialMessage'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('contextSize' in value) || value['contextSize'] === undefined) return false;
    if (!('additionalLlamacppServerParams' in value) || value['additionalLlamacppServerParams'] === undefined) return false;
    if (!('prependNoThinkTagToBeginningOfEachMessage' in value) || value['prependNoThinkTagToBeginningOfEachMessage'] === undefined) return false;
    return true;
}

export function CreateModelFromJSON(json: any): CreateModel {
    return CreateModelFromJSONTyped(json, false);
}

export function CreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'],
        'url': json['url'],
        'apiKey': json['apiKey'],
        'modelName': json['modelName'],
        'isDefault': json['isDefault'],
        'modelTypeId': json['modelTypeId'],
        'initialMessage': json['initialMessage'],
        'filePath': json['filePath'],
        'contextSize': json['contextSize'],
        'additionalLlamacppServerParams': json['additionalLlamacppServerParams'],
        'prependNoThinkTagToBeginningOfEachMessage': json['prependNoThinkTagToBeginningOfEachMessage'],
    };
}

export function CreateModelToJSON(json: any): CreateModel {
    return CreateModelToJSONTyped(json, false);
}

export function CreateModelToJSONTyped(value?: CreateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'url': value['url'],
        'apiKey': value['apiKey'],
        'modelName': value['modelName'],
        'isDefault': value['isDefault'],
        'modelTypeId': value['modelTypeId'],
        'initialMessage': value['initialMessage'],
        'filePath': value['filePath'],
        'contextSize': value['contextSize'],
        'additionalLlamacppServerParams': value['additionalLlamacppServerParams'],
        'prependNoThinkTagToBeginningOfEachMessage': value['prependNoThinkTagToBeginningOfEachMessage'],
    };
}

