/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Datasource
 */
export interface Datasource {
    /**
     * 
     * @type {number}
     * @memberof Datasource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Datasource
     */
    pathToChromaFile: string;
    /**
     * 
     * @type {string}
     * @memberof Datasource
     */
    createdDate: string;
    /**
     * 
     * @type {number}
     * @memberof Datasource
     */
    datasourceTypeId: number;
    /**
     * 
     * @type {string}
     * @memberof Datasource
     */
    name: string;
}

/**
 * Check if a given object implements the Datasource interface.
 */
export function instanceOfDatasource(value: object): value is Datasource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('pathToChromaFile' in value) || value['pathToChromaFile'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    if (!('datasourceTypeId' in value) || value['datasourceTypeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DatasourceFromJSON(json: any): Datasource {
    return DatasourceFromJSONTyped(json, false);
}

export function DatasourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Datasource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pathToChromaFile': json['pathToChromaFile'],
        'createdDate': json['createdDate'],
        'datasourceTypeId': json['datasourceTypeId'],
        'name': json['name'],
    };
}

export function DatasourceToJSON(json: any): Datasource {
    return DatasourceToJSONTyped(json, false);
}

export function DatasourceToJSONTyped(value?: Datasource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pathToChromaFile': value['pathToChromaFile'],
        'createdDate': value['createdDate'],
        'datasourceTypeId': value['datasourceTypeId'],
        'name': value['name'],
    };
}

