/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatasourceType
 */
export interface DatasourceType {
    /**
     * 
     * @type {number}
     * @memberof DatasourceType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DatasourceType
     */
    datasourceType: string;
}

/**
 * Check if a given object implements the DatasourceType interface.
 */
export function instanceOfDatasourceType(value: object): value is DatasourceType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('datasourceType' in value) || value['datasourceType'] === undefined) return false;
    return true;
}

export function DatasourceTypeFromJSON(json: any): DatasourceType {
    return DatasourceTypeFromJSONTyped(json, false);
}

export function DatasourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasourceType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'datasourceType': json['datasourceType'],
    };
}

export function DatasourceTypeToJSON(json: any): DatasourceType {
    return DatasourceTypeToJSONTyped(json, false);
}

export function DatasourceTypeToJSONTyped(value?: DatasourceType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'datasourceType': value['datasourceType'],
    };
}

