/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateAiImageRequest
 */
export interface GenerateAiImageRequest {
    /**
     * 
     * @type {number}
     * @memberof GenerateAiImageRequest
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof GenerateAiImageRequest
     */
    width: number;
    /**
     * 
     * @type {string}
     * @memberof GenerateAiImageRequest
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateAiImageRequest
     */
    prefix: string;
}

/**
 * Check if a given object implements the GenerateAiImageRequest interface.
 */
export function instanceOfGenerateAiImageRequest(value: object): value is GenerateAiImageRequest {
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    return true;
}

export function GenerateAiImageRequestFromJSON(json: any): GenerateAiImageRequest {
    return GenerateAiImageRequestFromJSONTyped(json, false);
}

export function GenerateAiImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateAiImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'],
        'width': json['width'],
        'prompt': json['prompt'],
        'prefix': json['prefix'],
    };
}

export function GenerateAiImageRequestToJSON(json: any): GenerateAiImageRequest {
    return GenerateAiImageRequestToJSONTyped(json, false);
}

export function GenerateAiImageRequestToJSONTyped(value?: GenerateAiImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'width': value['width'],
        'prompt': value['prompt'],
        'prefix': value['prefix'],
    };
}

