/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateAndReturnAiImageResponse
 */
export interface GenerateAndReturnAiImageResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerateAndReturnAiImageResponse
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateAndReturnAiImageResponse
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateAndReturnAiImageResponse
     */
    promptId: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateAndReturnAiImageResponse
     */
    prompt: string;
}

/**
 * Check if a given object implements the GenerateAndReturnAiImageResponse interface.
 */
export function instanceOfGenerateAndReturnAiImageResponse(value: object): value is GenerateAndReturnAiImageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GenerateAndReturnAiImageResponseFromJSON(json: any): GenerateAndReturnAiImageResponse {
    return GenerateAndReturnAiImageResponseFromJSONTyped(json, false);
}

export function GenerateAndReturnAiImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateAndReturnAiImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'mimeType': json['mimeType'],
        'promptId': json['promptId'],
        'prompt': json['prompt'],
    };
}

export function GenerateAndReturnAiImageResponseToJSON(json: any): GenerateAndReturnAiImageResponse {
    return GenerateAndReturnAiImageResponseToJSONTyped(json, false);
}

export function GenerateAndReturnAiImageResponseToJSONTyped(value?: GenerateAndReturnAiImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'mimeType': value['mimeType'],
        'promptId': value['promptId'],
        'prompt': value['prompt'],
    };
}

