/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAutoCompleteSuggestionsRequest
 */
export interface GetAutoCompleteSuggestionsRequest {
    /**
     * 
     * @type {string}
     * @memberof GetAutoCompleteSuggestionsRequest
     */
    text: string;
}

/**
 * Check if a given object implements the GetAutoCompleteSuggestionsRequest interface.
 */
export function instanceOfGetAutoCompleteSuggestionsRequest(value: object): value is GetAutoCompleteSuggestionsRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function GetAutoCompleteSuggestionsRequestFromJSON(json: any): GetAutoCompleteSuggestionsRequest {
    return GetAutoCompleteSuggestionsRequestFromJSONTyped(json, false);
}

export function GetAutoCompleteSuggestionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAutoCompleteSuggestionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function GetAutoCompleteSuggestionsRequestToJSON(json: any): GetAutoCompleteSuggestionsRequest {
    return GetAutoCompleteSuggestionsRequestToJSONTyped(json, false);
}

export function GetAutoCompleteSuggestionsRequestToJSONTyped(value?: GetAutoCompleteSuggestionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

