/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HaveAINameTheConversationRequest
 */
export interface HaveAINameTheConversationRequest {
    /**
     * 
     * @type {string}
     * @memberof HaveAINameTheConversationRequest
     */
    conversationName: string;
}

/**
 * Check if a given object implements the HaveAINameTheConversationRequest interface.
 */
export function instanceOfHaveAINameTheConversationRequest(value: object): value is HaveAINameTheConversationRequest {
    if (!('conversationName' in value) || value['conversationName'] === undefined) return false;
    return true;
}

export function HaveAINameTheConversationRequestFromJSON(json: any): HaveAINameTheConversationRequest {
    return HaveAINameTheConversationRequestFromJSONTyped(json, false);
}

export function HaveAINameTheConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HaveAINameTheConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationName': json['conversationName'],
    };
}

export function HaveAINameTheConversationRequestToJSON(json: any): HaveAINameTheConversationRequest {
    return HaveAINameTheConversationRequestToJSONTyped(json, false);
}

export function HaveAINameTheConversationRequestToJSONTyped(value?: HaveAINameTheConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationName': value['conversationName'],
    };
}

