/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HFModelSibling
 */
export interface HFModelSibling {
    /**
     * 
     * @type {string}
     * @memberof HFModelSibling
     */
    rfilename: string;
}

/**
 * Check if a given object implements the HFModelSibling interface.
 */
export function instanceOfHFModelSibling(value: object): value is HFModelSibling {
    if (!('rfilename' in value) || value['rfilename'] === undefined) return false;
    return true;
}

export function HFModelSiblingFromJSON(json: any): HFModelSibling {
    return HFModelSiblingFromJSONTyped(json, false);
}

export function HFModelSiblingFromJSONTyped(json: any, ignoreDiscriminator: boolean): HFModelSibling {
    if (json == null) {
        return json;
    }
    return {
        
        'rfilename': json['rfilename'],
    };
}

export function HFModelSiblingToJSON(json: any): HFModelSibling {
    return HFModelSiblingToJSONTyped(json, false);
}

export function HFModelSiblingToJSONTyped(value?: HFModelSibling | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rfilename': value['rfilename'],
    };
}

