/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlamaCppModelsDataMeta
 */
export interface LlamaCppModelsDataMeta {
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsDataMeta
     */
    vocabType: number;
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsDataMeta
     */
    nVocab: number;
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsDataMeta
     */
    nCtxTrain: number;
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsDataMeta
     */
    nEmbd: number;
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsDataMeta
     */
    nParams: number;
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsDataMeta
     */
    size: number;
}

/**
 * Check if a given object implements the LlamaCppModelsDataMeta interface.
 */
export function instanceOfLlamaCppModelsDataMeta(value: object): value is LlamaCppModelsDataMeta {
    if (!('vocabType' in value) || value['vocabType'] === undefined) return false;
    if (!('nVocab' in value) || value['nVocab'] === undefined) return false;
    if (!('nCtxTrain' in value) || value['nCtxTrain'] === undefined) return false;
    if (!('nEmbd' in value) || value['nEmbd'] === undefined) return false;
    if (!('nParams' in value) || value['nParams'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function LlamaCppModelsDataMetaFromJSON(json: any): LlamaCppModelsDataMeta {
    return LlamaCppModelsDataMetaFromJSONTyped(json, false);
}

export function LlamaCppModelsDataMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlamaCppModelsDataMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'vocabType': json['vocab_type'],
        'nVocab': json['n_vocab'],
        'nCtxTrain': json['n_ctx_train'],
        'nEmbd': json['n_embd'],
        'nParams': json['n_params'],
        'size': json['size'],
    };
}

export function LlamaCppModelsDataMetaToJSON(json: any): LlamaCppModelsDataMeta {
    return LlamaCppModelsDataMetaToJSONTyped(json, false);
}

export function LlamaCppModelsDataMetaToJSONTyped(value?: LlamaCppModelsDataMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vocab_type': value['vocabType'],
        'n_vocab': value['nVocab'],
        'n_ctx_train': value['nCtxTrain'],
        'n_embd': value['nEmbd'],
        'n_params': value['nParams'],
        'size': value['size'],
    };
}

