/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LlamaCppModelsData } from './LlamaCppModelsData';
import {
    LlamaCppModelsDataFromJSON,
    LlamaCppModelsDataFromJSONTyped,
    LlamaCppModelsDataToJSON,
    LlamaCppModelsDataToJSONTyped,
} from './LlamaCppModelsData';

/**
 * 
 * @export
 * @interface LlamaCppModelsResponse
 */
export interface LlamaCppModelsResponse {
    /**
     * 
     * @type {string}
     * @memberof LlamaCppModelsResponse
     */
    object: string;
    /**
     * 
     * @type {Array<LlamaCppModelsData>}
     * @memberof LlamaCppModelsResponse
     */
    data: Array<LlamaCppModelsData>;
}

/**
 * Check if a given object implements the LlamaCppModelsResponse interface.
 */
export function instanceOfLlamaCppModelsResponse(value: object): value is LlamaCppModelsResponse {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LlamaCppModelsResponseFromJSON(json: any): LlamaCppModelsResponse {
    return LlamaCppModelsResponseFromJSONTyped(json, false);
}

export function LlamaCppModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlamaCppModelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(LlamaCppModelsDataFromJSON)),
    };
}

export function LlamaCppModelsResponseToJSON(json: any): LlamaCppModelsResponse {
    return LlamaCppModelsResponseToJSONTyped(json, false);
}

export function LlamaCppModelsResponseToJSONTyped(value?: LlamaCppModelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(LlamaCppModelsDataToJSON)),
    };
}

