/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LlamaCppModelsDataMeta } from './LlamaCppModelsDataMeta';
import {
    LlamaCppModelsDataMetaFromJSON,
    LlamaCppModelsDataMetaFromJSONTyped,
    LlamaCppModelsDataMetaToJSON,
    LlamaCppModelsDataMetaToJSONTyped,
} from './LlamaCppModelsDataMeta';

/**
 * 
 * @export
 * @interface LlamaCppModelsData
 */
export interface LlamaCppModelsData {
    /**
     * 
     * @type {string}
     * @memberof LlamaCppModelsData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LlamaCppModelsData
     */
    object: string;
    /**
     * 
     * @type {number}
     * @memberof LlamaCppModelsData
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof LlamaCppModelsData
     */
    ownedBy: string;
    /**
     * 
     * @type {LlamaCppModelsDataMeta}
     * @memberof LlamaCppModelsData
     */
    meta: LlamaCppModelsDataMeta;
}

/**
 * Check if a given object implements the LlamaCppModelsData interface.
 */
export function instanceOfLlamaCppModelsData(value: object): value is LlamaCppModelsData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('ownedBy' in value) || value['ownedBy'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function LlamaCppModelsDataFromJSON(json: any): LlamaCppModelsData {
    return LlamaCppModelsDataFromJSONTyped(json, false);
}

export function LlamaCppModelsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlamaCppModelsData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'ownedBy': json['owned_by'],
        'meta': LlamaCppModelsDataMetaFromJSON(json['meta']),
    };
}

export function LlamaCppModelsDataToJSON(json: any): LlamaCppModelsData {
    return LlamaCppModelsDataToJSONTyped(json, false);
}

export function LlamaCppModelsDataToJSONTyped(value?: LlamaCppModelsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'owned_by': value['ownedBy'],
        'meta': LlamaCppModelsDataMetaToJSON(value['meta']),
    };
}

