/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmFile
 */
export interface LlmFile {
    /**
     * 
     * @type {string}
     * @memberof LlmFile
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof LlmFile
     */
    filePath: string;
    /**
     * 
     * @type {number}
     * @memberof LlmFile
     */
    fileSizeGB: number;
    /**
     * 
     * @type {string}
     * @memberof LlmFile
     */
    createdDate: string;
}

/**
 * Check if a given object implements the LlmFile interface.
 */
export function instanceOfLlmFile(value: object): value is LlmFile {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('fileSizeGB' in value) || value['fileSizeGB'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    return true;
}

export function LlmFileFromJSON(json: any): LlmFile {
    return LlmFileFromJSONTyped(json, false);
}

export function LlmFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmFile {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'filePath': json['filePath'],
        'fileSizeGB': json['fileSizeGB'],
        'createdDate': json['createdDate'],
    };
}

export function LlmFileToJSON(json: any): LlmFile {
    return LlmFileToJSONTyped(json, false);
}

export function LlmFileToJSONTyped(value?: LlmFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'fileSizeGB': value['fileSizeGB'],
        'createdDate': value['createdDate'],
    };
}

