/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    sentByUserId: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    messageText: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    createdDate: string;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('sentByUserId' in value) || value['sentByUserId'] === undefined) return false;
    if (!('messageText' in value) || value['messageText'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'],
        'sentByUserId': json['sentByUserId'],
        'messageText': json['messageText'],
        'createdDate': json['createdDate'],
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
        'sentByUserId': value['sentByUserId'],
        'messageText': value['messageText'],
        'createdDate': value['createdDate'],
    };
}

