/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    apiKey: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    modelName: string;
    /**
     * 
     * @type {boolean}
     * @memberof Model
     */
    isDefault: boolean;
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    modelTypeId: number;
}

/**
 * Check if a given object implements the Model interface.
 */
export function instanceOfModel(value: object): value is Model {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('modelTypeId' in value) || value['modelTypeId'] === undefined) return false;
    return true;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['displayName'],
        'url': json['url'],
        'apiKey': json['apiKey'],
        'modelName': json['modelName'],
        'isDefault': json['isDefault'],
        'modelTypeId': json['modelTypeId'],
    };
}

export function ModelToJSON(json: any): Model {
    return ModelToJSONTyped(json, false);
}

export function ModelToJSONTyped(value?: Model | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'url': value['url'],
        'apiKey': value['apiKey'],
        'modelName': value['modelName'],
        'isDefault': value['isDefault'],
        'modelTypeId': value['modelTypeId'],
    };
}

