/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelOrDatasourceOrPromptOrAgent
 */
export interface ModelOrDatasourceOrPromptOrAgent {
    /**
     * 
     * @type {string}
     * @memberof ModelOrDatasourceOrPromptOrAgent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelOrDatasourceOrPromptOrAgent
     */
    type: string;
}

/**
 * Check if a given object implements the ModelOrDatasourceOrPromptOrAgent interface.
 */
export function instanceOfModelOrDatasourceOrPromptOrAgent(value: object): value is ModelOrDatasourceOrPromptOrAgent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ModelOrDatasourceOrPromptOrAgentFromJSON(json: any): ModelOrDatasourceOrPromptOrAgent {
    return ModelOrDatasourceOrPromptOrAgentFromJSONTyped(json, false);
}

export function ModelOrDatasourceOrPromptOrAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelOrDatasourceOrPromptOrAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ModelOrDatasourceOrPromptOrAgentToJSON(json: any): ModelOrDatasourceOrPromptOrAgent {
    return ModelOrDatasourceOrPromptOrAgentToJSONTyped(json, false);
}

export function ModelOrDatasourceOrPromptOrAgentToJSONTyped(value?: ModelOrDatasourceOrPromptOrAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

