/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelOrDatasource
 */
export interface ModelOrDatasource {
    /**
     * 
     * @type {string}
     * @memberof ModelOrDatasource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelOrDatasource
     */
    type: string;
}

/**
 * Check if a given object implements the ModelOrDatasource interface.
 */
export function instanceOfModelOrDatasource(value: object): value is ModelOrDatasource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ModelOrDatasourceFromJSON(json: any): ModelOrDatasource {
    return ModelOrDatasourceFromJSONTyped(json, false);
}

export function ModelOrDatasourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelOrDatasource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ModelOrDatasourceToJSON(json: any): ModelOrDatasource {
    return ModelOrDatasourceToJSONTyped(json, false);
}

export function ModelOrDatasourceToJSONTyped(value?: ModelOrDatasource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

