/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelType
 */
export interface ModelType {
    /**
     * 
     * @type {number}
     * @memberof ModelType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ModelType
     */
    modelType: string;
}

/**
 * Check if a given object implements the ModelType interface.
 */
export function instanceOfModelType(value: object): value is ModelType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('modelType' in value) || value['modelType'] === undefined) return false;
    return true;
}

export function ModelTypeFromJSON(json: any): ModelType {
    return ModelTypeFromJSONTyped(json, false);
}

export function ModelTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'modelType': json['modelType'],
    };
}

export function ModelTypeToJSON(json: any): ModelType {
    return ModelTypeToJSONTyped(json, false);
}

export function ModelTypeToJSONTyped(value?: ModelType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'modelType': value['modelType'],
    };
}

