/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PollImageStatusResponse
 */
export interface PollImageStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof PollImageStatusResponse
     */
    imageName: string;
}

/**
 * Check if a given object implements the PollImageStatusResponse interface.
 */
export function instanceOfPollImageStatusResponse(value: object): value is PollImageStatusResponse {
    if (!('imageName' in value) || value['imageName'] === undefined) return false;
    return true;
}

export function PollImageStatusResponseFromJSON(json: any): PollImageStatusResponse {
    return PollImageStatusResponseFromJSONTyped(json, false);
}

export function PollImageStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollImageStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageName': json['imageName'],
    };
}

export function PollImageStatusResponseToJSON(json: any): PollImageStatusResponse {
    return PollImageStatusResponseToJSONTyped(json, false);
}

export function PollImageStatusResponseToJSONTyped(value?: PollImageStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageName': value['imageName'],
    };
}

