/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusTopic } from './StatusTopic';
import {
    StatusTopicFromJSON,
    StatusTopicFromJSONTyped,
    StatusTopicToJSON,
    StatusTopicToJSONTyped,
} from './StatusTopic';

/**
 * 
 * @export
 * @interface StatusTopicKeyValuesResponse
 */
export interface StatusTopicKeyValuesResponse {
    /**
     * 
     * @type {{ [key: string]: StatusTopic; }}
     * @memberof StatusTopicKeyValuesResponse
     */
    statusTopicsKeyValues: { [key: string]: StatusTopic; };
}

/**
 * Check if a given object implements the StatusTopicKeyValuesResponse interface.
 */
export function instanceOfStatusTopicKeyValuesResponse(value: object): value is StatusTopicKeyValuesResponse {
    if (!('statusTopicsKeyValues' in value) || value['statusTopicsKeyValues'] === undefined) return false;
    return true;
}

export function StatusTopicKeyValuesResponseFromJSON(json: any): StatusTopicKeyValuesResponse {
    return StatusTopicKeyValuesResponseFromJSONTyped(json, false);
}

export function StatusTopicKeyValuesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusTopicKeyValuesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusTopicsKeyValues': (mapValues(json['statusTopicsKeyValues'], StatusTopicFromJSON)),
    };
}

export function StatusTopicKeyValuesResponseToJSON(json: any): StatusTopicKeyValuesResponse {
    return StatusTopicKeyValuesResponseToJSONTyped(json, false);
}

export function StatusTopicKeyValuesResponseToJSONTyped(value?: StatusTopicKeyValuesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusTopicsKeyValues': (mapValues(value['statusTopicsKeyValues'], StatusTopicToJSON)),
    };
}

