/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMemberPrompt
 */
export interface UpdateMemberPrompt {
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberPrompt
     */
    promptName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberPrompt
     */
    promptText?: string;
}

/**
 * Check if a given object implements the UpdateMemberPrompt interface.
 */
export function instanceOfUpdateMemberPrompt(value: object): value is UpdateMemberPrompt {
    return true;
}

export function UpdateMemberPromptFromJSON(json: any): UpdateMemberPrompt {
    return UpdateMemberPromptFromJSONTyped(json, false);
}

export function UpdateMemberPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberPrompt {
    if (json == null) {
        return json;
    }
    return {
        
        'promptName': json['promptName'] == null ? undefined : json['promptName'],
        'promptText': json['promptText'] == null ? undefined : json['promptText'],
    };
}

export function UpdateMemberPromptToJSON(json: any): UpdateMemberPrompt {
    return UpdateMemberPromptToJSONTyped(json, false);
}

export function UpdateMemberPromptToJSONTyped(value?: UpdateMemberPrompt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptName': value['promptName'],
        'promptText': value['promptText'],
    };
}

