/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpscaleImageRequest
 */
export interface UpscaleImageRequest {
    /**
     * 
     * @type {string}
     * @memberof UpscaleImageRequest
     */
    imageName: string;
}

/**
 * Check if a given object implements the UpscaleImageRequest interface.
 */
export function instanceOfUpscaleImageRequest(value: object): value is UpscaleImageRequest {
    if (!('imageName' in value) || value['imageName'] === undefined) return false;
    return true;
}

export function UpscaleImageRequestFromJSON(json: any): UpscaleImageRequest {
    return UpscaleImageRequestFromJSONTyped(json, false);
}

export function UpscaleImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpscaleImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'imageName': json['imageName'],
    };
}

export function UpscaleImageRequestToJSON(json: any): UpscaleImageRequest {
    return UpscaleImageRequestToJSONTyped(json, false);
}

export function UpscaleImageRequestToJSONTyped(value?: UpscaleImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageName': value['imageName'],
    };
}

