/* tslint:disable */
/* eslint-disable */
/**
 * AI API
 * API to manage to interact with AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Url
 */
export interface Url {
    /**
     * The unique identifier for the shortened URL
     * @type {string}
     * @memberof Url
     */
    id: string;
    /**
     * The original URL that was shortened
     * @type {string}
     * @memberof Url
     */
    originalUrl: string;
    /**
     * The timestamp when the URL was created
     * @type {string}
     * @memberof Url
     */
    createdAt: string;
    /**
     * The full shortened URL
     * @type {string}
     * @memberof Url
     */
    shortUrl: string;
}

/**
 * Check if a given object implements the Url interface.
 */
export function instanceOfUrl(value: object): value is Url {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('originalUrl' in value) || value['originalUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('shortUrl' in value) || value['shortUrl'] === undefined) return false;
    return true;
}

export function UrlFromJSON(json: any): Url {
    return UrlFromJSONTyped(json, false);
}

export function UrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): Url {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'originalUrl': json['originalUrl'],
        'createdAt': json['createdAt'],
        'shortUrl': json['shortUrl'],
    };
}

export function UrlToJSON(json: any): Url {
    return UrlToJSONTyped(json, false);
}

export function UrlToJSONTyped(value?: Url | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'originalUrl': value['originalUrl'],
        'createdAt': value['createdAt'],
        'shortUrl': value['shortUrl'],
    };
}

